language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: nosetests --with-coverage --cover-inclusive
before_install:
  - pip install codecov
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5391c8616bc6f608fbc9
    on_success: always
    on_failure: always
    on_start: never