site_name: PyHDL
theme: 'readthedocs'
pages:
- Introduction: 'index.md'
- Wires: 'wire.md'
- Defining your own gates: 'modules.md'
- Builtin Gates:
  - Nand Gate: 'builtins/nand.md'
  - And Gate: 'builtins/and.md'
  - Nor Gate: 'builtins/nor.md'
  - Or Gate: 'builtins/or.md'
  - Xor Gate: 'builtins/xor.md'
  - Not Gate: 'builtins/not.md'
  - D Flip Flop: 'builtins/dff.md'
